---
# tasks file for abyres.ambari-server

# forked from https://github.com/seanorama/ansible-ambari

- name: install ambari-server
  yum: name=ambari-server state=latest

- name: Ensure ambari-server is stopped
  service: name=ambari-server state=stopped

- name: install git
  yum: name=git state=latest

- name : Create folder
  file : dest=/opt/ambari-install state=directory mode=0755

- name: setup ambari-server
  shell: ambari-server setup -s -j {{ java_home }}
  when: install_default

#- name: configure ambari-server
#  shell: creates=/opt/ambari-install/ambari-install-output ambari-server setup -j {{ java_home }} -s > /opt/ambari-install/ambari-install-output executable=/bin/bash
#  environment:
#    JAVA_HOME: "{{ java_home }}"
#  when: install_default

- name: configure ambari-server with remote metadata
  shell: creates=/opt/ambari-install/ambari-install-output ambari-server setup -j {{ java_home }} --database=postgres --databasehost={{ db_hostname }} --databaseport={{ db_port }} --databasename=ambari --postgresschema=ambari --databaseusername=ambari --databasepassword=bigdata -s > /opt/ambari-install/ambari-install-output executable=/bin/bash
  environment:
    JAVA_HOME: "{{ java_home }}"
  when: not install_default

- name: install postgresql
  yum: name=postgresql state=latest
  when: not install_default

#- name : check if ambari-server is installed
#  wait_for : path=/opt/ambari-install/ambari-install-output search_regex="completed successfully"

- name: install ambari services
  git: repo={{ item.repo }} dest=/var/lib/ambari-server/resources/stacks/HDP/{{ item.hdp_version }}/services/{{ item.label }} 
  with_items: "{{ service_extensions }}"
#  ignore_errors: yes

#- name : configure postgresql driver
#  shell: creates=/opt/ambari-install/ambari-postgresql-setup-output ambari-server setup -j {{ java_home }} -s --jdbc-db=postgres --jdbc-driver=/usr/lib/ambari-server/postgresql-9.3-1101-jdbc4.jar > /opt/ambari-install/ambari-postgresql-setup-output executable=/bin/bash
#  environment:
#    JAVA_HOME: "{{ java_home }}"

#- name: install maven
#  yum: name=maven

#- name : Create folder
#  file : dest=/opt/iframe-view/ state=directory mode=0755
#
#- name: clone ambari-iframe repository
#  git: repo=https://github.com/hortonworks-gallery/ambari-iframe-view.git dest=/opt/iframe-view/ambari-iframe-view

#- include: build-view.yml
#  with_items: "{{ iframe_views }}"
- name: pausing for 30 seconds
  pause: 
    seconds: 30

- name: start ambari server
  command: ambari-server restart

- name: check if ambari-server is up
  wait_for: port=8080 delay=10

# endfork

- name: copy ssh private to server
  copy: src={{ private_key }} dest=/root/.ssh/id_rsa mode=0600
