---
# tasks file for abyres.ntpd
#
- name: install ntp
  yum: name=ntp,ntpdate state=latest

- name: set timezone
  command: timedatectl set-timezone {{ timezone }}

- name: configure ntp 
  template: src=ntp.conf_tmpl dest=/etc/ntp.conf mode=0644

- name: start ntp service
  service: name=ntpd state=restarted enabled=yes
