---
# tasks file for abyres.hdf-ambari-server

- name: install ambari-server
  yum: name=ambari-server state=latest

- name: Ensure ambari-server is stopped
  service: name=ambari-server state=stopped

- name: install git
  yum: name=git state=latest

- name : Create folder
  file : dest=/opt/ambari-install state=directory mode=0755

- name: setup ambari-server
  shell: ambari-server setup -s -j {{ java_home }}

- name: backup ambari resources
  shell: cp -r /var/lib/ambari-server/resources /var/lib/ambari-server/resources.backup

- name: install mpack
  shell: ambari-server install-mpack --mpack={{ hdf_mpack_url }} --purge --verbose

- name: pausing for 30secs
  pause: 
    seconds: 30

- name: start ambari-server
  command: ambari-server restart

- name: check if ambari-server is up
  wait_for: port=8080 delay=10

